
# TESTING DO NOT TOUCH
test:
  - -261 # X
  - 89   # Y
  - 250  # Z

# GHOST RESPAWN CONFIG
# Should not be touched manually, use
# commands through ChampionCrusader

MAP_ONE_FIRST: "RED"
MAP_ONE_FIRST_LOC:
  - -261 # X
  - 89   # Y
  - 250  # Z

MAP_ONE_SECOND: "BLUE"
MAP_ONE_SECOND_LOC:
  - -261 # X
  - 89   # Y
  - 250  # Z

MAP_TWO_FIRST: "GREEN"
MAP_TWO_FIRST_LOC:
  - -261 # X
  - 89   # Y
  - 250  # Z

MAP_TWO_SECOND: "YELLOW"
MAP_TWO_SECOND_LOC:
  - -261 # X
  - 89   # Y
  - 250  # Z

MAP_THREE_FIRST: "PURPLE"
MAP_THREE_FIRST_LOC:
  - -261 # X
  - 89   # Y
  - 250  # Z

MAP_THREE_SECOND: "PINK"
MAP_THREE_SECOND_LOC:
  - -261 # X
  - 89   # Y
  - 250  # Z

MAP_FOUR_FIRST: "ORANGE"
MAP_FOUR_FIRST_LOC:
  - -261 # X
  - 89   # Y
  - 250  # Z

MAP_FOUR_SECOND: "CYAN"
MAP_FOUR_SECOND_LOC:
  - -261 # X
  - 89   # Y
  - 250  # Z

