# GHOST RESPAWN CONFIG
# Should not be touched manually, use
# commands through ChampionCrusader

RED:
  - 1
  - 1
BLUE:
  - 1
  - 2
GREEN:
  - 2
  - 2
YELLOW:
  - 2
  - 1
PURPLE:
  - 3
  - 1
PINK:
  - 3
  - 2
ORANGE:
  - 4
  - 1
CYAN:
  - 4
  - 2

# X
# Y
# Z
1:
  - -563
  - 105
  - 11

2:
  - -886
  - 107
  - 11

3:
  - -1202
  - 109
  - 11

4:
  - -1537
  - 111
  - 11