name: ChampionCrusader
version: '${project.version}'
main: me.mcss.championcrusader.ChampionCrusader
api-version: 1.16
authors: [ Itzahria, Rapid64, Guidance , JupiterInMay ]
description: The complete plugin for Champion Crusader, other code may be found in the server data packs.
website: https://twitter.com/mcsstwt
commands:
  berserker:
    description: Set the subclass of the player to [BERSERKER]
    usage: /<command>
  paladin:
    description: Set the subclass of the player to [PALADIN]
    usage: /<command>
  mage:
    description: Set the subclass of the player to [MAGE]
    usage: /<command>
  ranger:
    description: Set the subclass of the player to [RANGER]
    usage: /<command>
  cc:
    description: Use setteam [Player] [Team Color] to set a players Champion Crusader team
    usage: /<command>
  teams:
    description: Show all the current registered players with their TEAM and if chosen CLASS
    usage: /<command>